---
title: "Background"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

## Professional Skills

- **Computer:** R, Microsoft (Word, PowerPoint, Excel)
- **Technical:** Data Management, Research, Technical Writing
- **Professional:** CPR

## Advanced Courses Taken

- EDCI 404: McNair Graduate School Prep
- EDCI 504: McNair Advanced Research Methods
- NRS 499: Renewable Energy Design and Economics
- ESM 201: Ecological Principals
- ESM 202: Environmental Biogeochemistry
- ESM 203: Earth System Science
- ESM 206: Data Analysis and Statistics
- ESM 210: Business and the Environment
- ESM 241: Environmental Politics and Policy
- ESM 244: Advanced Data Analysis
- ESM 256A: Eco-Entrepreneurship

## Research

[**The Contemporary Precedence of Building-Applied Photovoltaic Systems: A Multileveled Review to Derive a Holistic Cost-Benefit Analysis**](https://s3.amazonaws.com/handshake.production/documents/documents/020/186/655/original/Simms_UofI_Undergraduate_Thesis.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAILGI2B7PIOQKG5EA%2F20210209%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210209T135917Z&X-Amz-Expires=10&X-Amz-SignedHeaders=host&X-Amz-Signature=0224e7f4b28c49589072445c03718233920a6bdca1e652330381cf1d7a370303) - Carlos Simms 2020

A capstone report on the salience of building-applied photovoltaic (BAPV) systems, via an analysis of four distinct levels of significance: the university, state, national, and international levels. As global greenhouse gas (GHG) emissions continue to rise and contribute to anthropogenic climate change, a clear global commons issue is outlined: a need for a global transition to renewable energy to mitigate energy-sector GHG emissions. A focus on solar technology, specifically that of BAPV systems, as a first step in transitioning to a renewable energy paradigm, is provided. BAPV systems are the cheapest solar energy variant and are integrable with existing infrastructure on a mass-scale unlike that of any other renewable energy technology. A cost-benefit analysis to solar energy use concluded that the free-market and governments both play integral roles in propagating the market viability of solar energy. In addition, practical, economic, sociocultural, political, and environmental elements of solar technology use are outlined, boasting of substantial promise and warning of salient issues looking ahead into the future. 

[**The African Union’s Adaptability and Resiliency to Climate Change and Associated Population Displacement**](https://s3.amazonaws.com/handshake.production/documents/documents/020/186/689/original/Simms_UofI_Undergraduate_Issue_Brief.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAILGI2B7PIOQKG5EA%2F20210209%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210209T135839Z&X-Amz-Expires=10&X-Amz-SignedHeaders=host&X-Amz-Signature=e09e97be3a0cda791521643c5a0d8286788ea6c1403d86d7c70f7fca67aa43c9) - Carlos Simms 2020

An issue brief on the African Union's ability to adapt to, and rebound from, perturbations caused by climate change. In Africa, refugees are fleeing from extreme poverty, food scarcity, poor governmental institutions, war, religious and political persecution, and abysmal environmental conditions that will further be worsened by climate change. In consequence, mass migration routes are commonplace across Africa, constituting an already salient population displacement issue. In association, there is a growing concern over the potential for a massive climate refugee crisis as climate change is perturbing already deficient ecosystem services and policial institutions. A brief assessment of the African Union's role in climate adaptability and resiliency, resulted in questionable authority and passive policy rhetoric regarding the union's efficacy in provisioning for such a crisis.

## Lifetime Grants and Awards

- Environmental Science and Management Graduate Scholarship ($69,804)
- Ronald E. McNair Post-Baccalaureate Achievement Research Grant ($3,500)
- DeVlieg Foundation Research Grant ($3,000)
- Ramseyer/Daly General Scholarship ($779)
- Honors Scholars Endowment ($200)
- Monnett, Wallace and Dorothy Scholarship ($1,000)
- Henry, Mary Lillian Scholarship ($494)
- Phi Eta Sigma Honors Scholarship ($100)
- Academic Achievement Level Scholarship ($1,727)