---
title: "Documents"
---

## Academic Accreditations

- **Bachelor of Science in Environmental Science** [Link](simms_diploma_environmental_science_bachelors.pdf)

- **Academic Certificate in Climate Change** [Link](simms_diploma_climate_change_certificate.pdf)

## Official Records

- **Transcript - University of California Santa Barbara** [Link](simms_official_transcript_university_of_california_santa_barbara.pdf)

- **Enrollment Verification - University of California Santa Barbara** [Link](simms_official_enrollment_verification_university_of_california_santa_barbara.pdf)

- **Transcript - University of Idaho** [Link](simms_official_transcript_university_of_idaho.pdf)

## Academic Research

- **Floating Solar in Santa Barbara: Technical-Economic Analysis and Feasibility Report** *(March 2022)*

- **The Contemporary Precedence of Building-Applied Photovoltaic Systems: A Multileveled Review to Derive a Holistic Cost-Benefit Analysis** *(January 2020)* [Link](simms_thesis_university_of_idaho.pdf)

- **The African Union’s Adaptability and Resiliency to Climate Change and Associated Population Displacement** *(January 2020)* [Link](simms_issue_brief_university_of_idaho.pdf)
